_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 7c1eea93-7b7f-4be7-a2cd-2a0a60dbf3dc
name: 'Selectra - Covid Vaccination Center'
mail: admin@example.com
slogan: ''
page:
  403: /node/36
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
